site_name: Python wrapper for X-Plane Web API

theme:
  name: "material"
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to system preference
  logo: x-plane.svg

nav:
- Home:
  - Overview: index.md
  - Changelog: changelog.md
- Usage: usage/index.md
- Reference: reference/index.md

markdown_extensions:
- pymdownx.snippets

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            # backlinks: tree
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            # extensions: [scripts/griffe_extensions.py]
            filters: public
            heading_level: 1
            inherited_members: true
            line_length: 88
            merge_init_into_class: true
            parameter_headings: true
            preload_modules: [mkdocstrings]
            relative_crossrefs: true
            scoped_crossrefs: true
            separate_signature: true
            show_bases: false
            show_inheritance_diagram: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            unwrap_annotated: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
