site_name: Python wrapper for X-Plane Web API

theme:
  name: "material"
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to system preference
  logo: material/plane

nav:
  - Welcome: index.md
  - Dataref: dataref.md
  - Command: command.md
  - REST API: rest_api.md
  - Websocket API: ws_api.md
  - X-Plane Beacon Monitor: beacon.md


plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
