site_name: Python wrapper for X-Plane Web API

theme:
  name: "material"
  palette:
    scheme: slate
    primary: indigo
    accent: orange
#  logo: plane

nav:
  - Welcome: index.md
  - Dataref: dataref.md
  - Command: command.md
  - REST API: rest_api.md
  - Websocket API: ws_api.md
  - X-Plane Beacon Monitor: beacon.md


plugins:
  - mkdocstrings

